#!/usr/bin/env python

import os
import subprocess
import sys
import tempfile

filename = sys.argv[1]

assert filename.endswith('.md')

with open(filename) as input:
    os.makedirs('build', exist_ok=True)
    os.chdir('build')

    filename = os.path.basename(filename)
    filename = filename[:-3].capitalize()

    with open(filename, 'w') as output:
        # Currently printing an indented code block.
        code = False

        for line in input.readlines():
            if line.startswith('    '):
                output.write(line[4:])
                code = True
            elif code:
                output.write('\n')
                code = False

subprocess.run(['ghci', filename])
