#!/usr/bin/env python3

import os
import sys

if len(sys.argv) != 2:
    sys.stderr.write(f'usage: {sys.argv[0]} [file]\n')
    sys.exit(0)

filename = sys.argv[1]

if not filename.endswith('.md'):
    sys.stderr.write(f'invalid target {repr(filename)}\n')
    sys.exit(0)

file = open(filename, 'r')

# Note that filename ends with `.md`.
dir = os.path.basename(filename)[:-3]

os.makedirs(f'.build/{dir}', exist_ok=True)
os.chdir(f'.build/{dir}')

files = {}
current = None

for line in file:
    if line.startswith('```'):
        # Note that `line` ends with a new line.
        if len(line) > 4:
            filename = line[3:-1]
            if filename not in files:
                files[filename] = open(filename, 'w')
            current = files[filename]
        elif current:
            current.write('\n')
            current = None
    # Note that using `elif` avoids writing the line with the file name to the
    # output.
    elif current:
        current.write(line)

file.close()

for filename, file in files.items():
    sys.stdout.write(f'.build/{dir}/{filename}\n')
    file.close()
