#!/usr/bin/env python3

import os
import subprocess
import sys
import tempfile

if len(sys.argv) != 2:
    sys.stderr.write(f"usage: {sys.argv[0]} [file]\n")
    sys.exit(0)

filename = sys.argv[1]

if not filename.endswith('.md'):
    sys.stderr.write(f"cannot run {repr(filename)}\n")
    sys.exit(0)

with open(filename) as input:
    os.makedirs('build', exist_ok=True)
    os.chdir('build')

    filename = os.path.basename(filename)
    # Remove `.md` from filename.
    filename = filename[:-3]

    with open(filename, 'w') as output:
        for line in input.readlines():
            if line.startswith('    '):
                output.write(line[4:])
            else:
                output.write('\n')

if filename.endswith('.hs'):    subprocess.run(['ghci', filename])
if filename.endswith('.lean'):  subprocess.run(['lean', filename])
